import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DotPatternWithGlowEffectDemo } from "@/components/magicui/background";
import { ReactElement, ReactNode } from 'react';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: 'swap',
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">  
      <body className="antialiased">
        <DotPatternWithGlowEffectDemo>
          <div className={`${geistSans.variable} ${geistMono.variable}`}>
            {children}
          </div>
        </DotPatternWithGlowEffectDemo>
      </body>
    </html>
  );
}
